# Generated by Django 2.1.7 on 2019-03-28 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uks', '0003_auto_20190328_1612'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IssueAssignments',
            new_name='IssueAssignment',
        ),
        migrations.RenameModel(
            old_name='UserProjects',
            new_name='IssueLabel',
        ),
        migrations.RenameModel(
            old_name='IssueLabels',
            new_name='UserProject',
        ),
        migrations.RemoveField(
            model_name='issuelabel',
            name='project',
        ),
        migrations.RemoveField(
            model_name='issuelabel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userproject',
            name='issue',
        ),
        migrations.RemoveField(
            model_name='userproject',
            name='label',
        ),
        migrations.AddField(
            model_name='issuelabel',
            name='issue',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='uks.Issue'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issuelabel',
            name='label',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='uks.Label'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userproject',
            name='project',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='uks.Project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userproject',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='uks.User'),
            preserve_default=False,
        ),
    ]
